app:
    resource: @AppBundle/Controller/
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
  type : rest
  resource : "routing_api.yml"
  prefix : /api